#!/usr/bin/env node
// GENERATED — npm run build:plugin. Do not edit this file directly.
// Source: packages/adapter-claude/src/hooks/postToolUse.ts


// packages/adapter-claude/src/hooks/postToolUse.ts
var DEFAULT_PORT = 4177;
var POST_TIMEOUT_MS = 500;
var STDIN_TIMEOUT_MS = 2e3;
var HARD_EXIT_TIMEOUT_MS = 3500;
var FLAGS_TIMEOUT_MS = 500;
var hardExitTimer = setTimeout(() => {
  process.exit(0);
}, HARD_EXIT_TIMEOUT_MS);
async function readStdin() {
  const chunks = [];
  const collect = (async () => {
    for await (const chunk of process.stdin) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    }
  })();
  const timeout = new Promise((resolve) => {
    const t = setTimeout(resolve, STDIN_TIMEOUT_MS);
    t.unref();
  });
  await Promise.race([collect, timeout]);
  return Buffer.concat(chunks).toString("utf8");
}
function tolerantParse(raw) {
  try {
    return JSON.parse(raw);
  } catch {
    return void 0;
  }
}
function resolvePort() {
  const envPort = process.env.SOJOURN_PORT;
  if (envPort) {
    const parsed = Number.parseInt(envPort, 10);
    if (Number.isFinite(parsed) && parsed > 0) return parsed;
  }
  return DEFAULT_PORT;
}
async function postToDaemon(payload) {
  const port = resolvePort();
  const url = `http://localhost:${port}/api/hooks/claude`;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), POST_TIMEOUT_MS);
  try {
    await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload ?? {}),
      signal: controller.signal
    });
  } finally {
    clearTimeout(timer);
  }
}
function stopEventSessionId(payload) {
  if (!payload || typeof payload !== "object") return null;
  const p = payload;
  if (p.hook_event_name !== "Stop") return null;
  return typeof p.session_id === "string" && p.session_id.length > 0 ? p.session_id : null;
}
async function fetchTurnFlagLines(sessionId) {
  const port = resolvePort();
  const url = `http://localhost:${port}/api/sessions/${encodeURIComponent(sessionId)}/turn-flags`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(FLAGS_TIMEOUT_MS) });
    if (!res.ok) return [];
    const data = await res.json();
    if (!data || typeof data !== "object") return [];
    const lines = data.lines;
    if (!Array.isArray(lines)) return [];
    return lines.filter((line) => typeof line === "string");
  } catch {
    return [];
  }
}
function writeAndWait(chunk) {
  return new Promise((resolve) => {
    const ok = process.stdout.write(chunk, () => {
      if (ok) resolve();
    });
    if (!ok) {
      process.stdout.once("drain", resolve);
    }
  });
}
async function printFlagLines(lines) {
  for (const line of lines) {
    if (line.toLowerCase().includes("advisory")) continue;
    await writeAndWait(`Sojourn: ${line}
`);
  }
}
async function main() {
  const raw = await readStdin();
  const payload = tolerantParse(raw);
  try {
    await postToDaemon(payload);
  } catch {
  }
  if (process.env.SOJOURN_HOOK_FLAGS === "1") {
    const sessionId = stopEventSessionId(payload);
    if (sessionId) {
      const lines = await fetchTurnFlagLines(sessionId);
      await printFlagLines(lines);
    }
  }
}
main().catch(() => {
}).finally(() => {
  clearTimeout(hardExitTimer);
  process.exit(0);
});
