#!/usr/bin/env node
// Bundles the Claude Code hook entrypoint into a self-contained, dependency-
// free ESM script for the distributable plugin
// (plugins/claude/hooks/sojourn-hook.mjs).
//
// Why: hooks.json used to invoke the hook via a path OUTSIDE the plugin
// directory (`${CLAUDE_PLUGIN_ROOT}/../../packages/adapter-claude/dist/...`),
// which only resolves when the plugin runs from an in-repo checkout with
// packages/adapter-claude already built. That breaks the second install
// mode — copying just plugins/claude/ out of the repo (marketplace /
// standalone install). This script esbuild-bundles the TypeScript hook
// source into one file with no runtime imports outside node builtins, so
// the plugin works either way.
//
// Usage: node scripts/build-plugin.mjs   (wired as `npm run build:plugin`)
// Requires: esbuild (root devDependency) — does not modify node_modules.

import { build } from "esbuild";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");

const ENTRY = path.join(REPO_ROOT, "packages/adapter-claude/src/hooks/postToolUse.ts");
const OUT_DIR = path.join(REPO_ROOT, "plugins/claude/hooks");
const OUT_FILE = path.join(OUT_DIR, "sojourn-hook.mjs");

const SHEBANG = "#!/usr/bin/env node";
const BANNER = [
  "// GENERATED — npm run build:plugin. Do not edit this file directly.",
  "// Source: packages/adapter-claude/src/hooks/postToolUse.ts",
].join("\n");

if (!fs.existsSync(ENTRY)) {
  console.error(`[build-plugin] entry not found: ${ENTRY}`);
  process.exit(1);
}
fs.mkdirSync(OUT_DIR, { recursive: true });

// No `banner` option here on purpose: the entry source (postToolUse.ts)
// starts with its own `#!/usr/bin/env node`, and esbuild automatically
// hoists a leading hashbang to line 1 of the output. A shebang is only
// valid on a file's very first line, so handing esbuild a banner shebang
// too would silently produce a file with TWO shebang lines — a syntax
// error at run time, not at build time. Instead we build plain, then
// normalize the shebang ourselves below regardless of whether the source
// happens to have one.
await build({
  entryPoints: [ENTRY],
  outfile: OUT_FILE,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "none",
  logLevel: "silent",
});

const rawContents = fs.readFileSync(OUT_FILE, "utf8");
const hasShebang = rawContents.startsWith("#!");
const body = hasShebang ? rawContents.slice(rawContents.indexOf("\n") + 1) : rawContents;
const contents = `${SHEBANG}\n${BANNER}\n\n${body}`;
fs.writeFileSync(OUT_FILE, contents, "utf8");

// esbuild output files aren't executable by default; the plugin invokes
// this file directly (no `node` prefix) via hooks.json's
// "${CLAUDE_PLUGIN_ROOT}/hooks/sojourn-hook.mjs", relying on the shebang.
fs.chmodSync(OUT_FILE, 0o755);

// Guardrail: the plugin must stay self-contained. If the hook source (owned
// by another workstream) grows an import esbuild couldn't inline into a
// node builtin — e.g. a bare npm package specifier — fail the build loudly
// instead of shipping a plugin that requires node_modules at runtime.
const importSpecifiers = [
  ...contents.matchAll(/^\s*import\s+(?:[^"']+?\s+from\s+)?["']([^"']+)["']/gm),
].map((m) => m[1]);
const builtinSet = new Set([...builtinModules, ...builtinModules.map((m) => `node:${m}`)]);
const badImports = importSpecifiers.filter((spec) => !builtinSet.has(spec));
if (badImports.length > 0) {
  console.error(
    `[build-plugin] bundle references non-builtin import(s), plugin would not be self-contained: ${badImports.join(", ")}`,
  );
  process.exit(1);
}

console.log(`[build-plugin] wrote ${path.relative(REPO_ROOT, OUT_FILE)} (${contents.length} bytes)`);
